[build]
  functions = "netlify/functions"
  
[build.environment]
  # Server-side Google Maps API key (unrestricted, secure)
  GOOGLE_MAPS_API_KEY = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200